#!/usr/bin/env bash
#? Save a page (commit and push)
#? Usage: tb2 page save -c CHAPTERNAME -b BOOKNAME -p PAGENAME [-q]
#? Opts:
#?   -b         BOOKNAME
#?   -c         CHAPTERNAME
#?   -p         PAGENAME
#? config dependencies: MDBOOK_SRC_DIR, TB2_OPERATION_BRANCH

set -euo pipefail


source "$ROOT/utils.sh"

bookName=""
chapterName=""
pageName=""

while getopts "b:c:p:q" opt; do
  case $opt in
  b)
    bookName="$OPTARG"
    ;;
  c)
    chapterName="$OPTARG"
    ;;
  p)
    pageName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

if [[ -z "${bookName}" ]] || [[ -z "${chapterName}" ]] || [[ -z "${pageName}" ]]; then
  warn "Options -b BOOKNAME, -c CHAPTERNAME, and -p PAGENAME are all required."
  info "Exit."
  exit 1
fi

log "Checking for config..."

useConf MDBOOK_SRC_DIR srcDir
useConf TB2_OPERATION_BRANCH branch

log "done."

pageFile="$srcDir/$bookName/$chapterName/$pageName.md"

info "Saving page: $pageName in chapter: $chapterName of book: $bookName"

log "Checking if page file exists..."
if [[ ! -f "$pageFile" ]]; then
  error "Page file '$pageFile' does not exist."
  info "Exit."
  exit 1
fi
log "done."
chapterBranch="chapter/$chapterName"
git_chkBranch "$chapterBranch"
log "Committing and pushing page changes..."
run git add "$pageFile"
run git commit -m "Page: $pageName in $chapterName"
log "done."

log "Pushing changes..."
run git push
log "done."

info "Page '$pageName' saved successfully."
exit 0
