#!/usr/bin/env bash

set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)"
source "$base_dir/utils.sh"

#--------------------------------#
#    TB2: TextBook ToolBox       #
#--------------------------------#

if ! mdbook.chkAvailable; then
  warn "Exit.."
  exit 1
fi

if ! gh.chkAvailable; then
  warn "Exit.."
  exit 1
fi

case "${1:-}" in
  ""|"-i")
    "$base_dir/interactive/main.sh" "${@:2}"
    ;;
  "--help"|"-h")
    "$base_dir/subcmds/help.d/help"
    ;;
  *)
    if [[ ! -f "$base_dir/subcmds/$1.d/$1"]] || [[ ! -x "$base_dir/subcmds/$1.d/$1" ]]; then
      warn "Unknown subcommand: $1"
      info "Run '$0 --help' for usage."
      exit 1
    fi
    "$base_dir/subcmds/$1.d/$1" "${@:2}"
    ;;
esac