#!/usr/bin/env bash
#? Usage: tb2 chapter <subcmd> [options]
#? Subcommands:
#?   new       Create a new chapter
#?   save      Save a chapter (create pull request)
#?   list      List chapters in a book

set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)/../.."
source "$base_dir/utils.sh"

case "${1:-}" in
  "")
    warn "No subcmd provided for 'chapter'"
    exit 1
    ;;
  "list")
    shift
    "$base_dir/subcmds/chapter.d/subcmds/list" "$@"
    ;;
  "new")
    shift
    "$base_dir/subcmds/chapter.d/subcmds/new" "$@"
    ;;
  "save")
    shift
    "$base_dir/subcmds/chapter.d/subcmds/save" "$@"
    ;;
  *)
    warn "Unknown subcmd '$1' for 'chapter'"
    exit 1
    ;;
esac
