#!/usr/bin/env bash
#? List chapters in a book
#? Usage: tb2 chapter list -b BOOKNAME
#? Opts:
#?   -b         BOOKNAME
#? config dependencies: MDBOOK_SRC_DIR

set -euo pipefail


source "$ROOT/utils.sh"

bookName=""

while getopts "b:" opt; do
  case $opt in
  b)
    bookName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

log "Checking for config..."
if [[ -z "$bookName" ]]; then
	error "-b option is required."
	exit 1
fi
useConf MDBOOK_SRC_DIR srcDir
useConf PROJECT_NAME projectName

log "done."

bookDir="$srcDir/$bookName"
echo "=== Local chapters ($bookName) ==="

shopt -s nullglob
for d in "$bookDir"/*/; do
  echo "- [$bookName] $(basename "$d")"
done
shopt -u nullglob

echo "=== Remote chapters ($bookName) ==="

if ! issues=$(gh_findIssue "$projectName" "Chapter:.*\($bookName\)"); then
  echo "No remote chapters."
else
  echo "$issues" | sed "s/^/- [$bookName] /"
fi
exit 0