#!/usr/bin/env bash
#? List chapters in a book
#? Usage: tb2 chapter list -b BOOKNAME
#? Opts:
#?   -b         BOOKNAME
#? config dependencies: MDBOOK_SRC_DIR

set -euo pipefail


source "$ROOT/utils.sh"

bookName=""

while getopts "b:" opt; do
  case $opt in
  b)
    bookName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

log "Checking for config..."
checkConf true "MDBOOK_SRC_DIR" "PROJECT_NAME"
useConf MDBOOK_SRC_DIR srcDir
useConf PROJECT_NAME projectName
mustVar true "srcDir" "projectName"
log "done."

bookDir="$srcDir/$bookName"

info "=Remote [GitHub Issues]="
log "=========================="
if gh_isManualMode; then
  info "Remote list is disabled in manual mode."
else
  run gh_findIssue "$projectName" "Chapter:"
fi
info "=Local [mdBook directory chapters in $bookName]="
log "=========================================="

if [[ ! -d "$bookDir" ]]; then
  warn "Book directory '$bookDir' does not exist."
  info "No chapters found."
else
  log "Listing directories in '$bookDir'..."
  if ls -d "$bookDir"/* >/dev/null 2>&1; then
		find "$bookDir" -maxdepth 1 -mindepth 1 -type d -print0 | while IFS= read -r -d '' chapterPath; do
			chapterPath=$(basename "$chapterPath")
			log "$chapterPath"
		done
  else
    info "No chapters found in '$bookName'."
  fi
fi
log "=========================================="
exit 0
