#!/usr/bin/env bash
#? Create a new chapter
#? Usage: tb2 chapter new -c CHAPTERNAME -b BOOKNAME 
#? Opts:
#?   -b         BOOKNAME
#?   -c         CHAPTERNAME
#? config dependencies: GH_OWNER_NAME, MDBOOK_SRC_DIR, TB2_OPERATION_BRANCH

set -euo pipefail


. "$ROOT/utils.sh"

bookName=""
chapterName=""
while getopts "b:c:" opt; do
  case $opt in
  b)
    bookName="$OPTARG"
    ;;
  c)
    chapterName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

if [ -z "${bookName}" ] || [ -z "${chapterName}" ]; then
  warn "Both -b BOOKNAME and -c CHAPTERNAME are required."
  info "Exit."
  exit 1
fi

log "Checking for config..."

useConf GH_OWNER_NAME name
useConf MDBOOK_SRC_DIR srcDir
useConf TB2_OPERATION_BRANCH branch


log "done."

chapterBranch="chapter/$chapterName"

info "Creating new chapter: $chapterName in book: $bookName"

log "Checking if book directory exists..."
if [ ! -d "$srcDir/$bookName" ]; then
  error "Book directory '$srcDir/$bookName' does not exist."
  info "Exit."
  exit 1
fi
log "done."

log "Searching for parent book Issue..."
if gh_isManualMode;then
	warn "this code uses gh issue list to get parent Book issue number."
	info "but now tb2 is manual mode."
	info "so please input directory, \"Book: $bookName\"'s issue number."
	bookIssueNum=$(ask "number")
else
	bookIssueNum=$(gh issue list --repo "$name/$repoName" --search "title:\"Book: $bookName\"" --json number --jq '.[0].number' 2>/dev/null || echo "")
fi
if [ -z "$bookIssueNum" ]; then
  warn "Could not find Book Issue for '$bookName'. Continuing without link."
  bookIssueBody="Chapter '$chapterName' in book '$bookName'"
else
  log "Found Book Issue #$bookIssueNum"
  bookIssueBody="Chapter '$chapterName' in book '$bookName'. Parent Issue: #$bookIssueNum"
fi

git_chkBranch "$chapterBranch"

log "Checking for local directory..."
chapterDir="$srcDir/$bookName/$chapterName"
if [ -d "$chapterDir" ]; then
  warn "Directory '$chapterDir' already exists locally. Skipping mkdir."
else
  log "Creating local directory '$chapterDir'..."
  run mkdir -p "$chapterDir"
  log "done."
fi

log "Creating GitHub issue for chapter..."
run gh_createIssue "$name/$repoName" "Chapter: $chapterName" "$bookIssueBody"
log "done."

ans=$(ask "Do you want to commit&push the repository now chapter branch? (y/n)")
if [ "$ans" != "y" ] && [ "$ans" != "Y" ]; then
  info "Exit."
  exit 0
fi

log "Committing and pushing changes..."
run git add "$chapterDir"
run git commit -m "Create chapter $chapterName"
run git push -u origin "$chapterBranch"
log "done."
info "New chapter '$chapterName' created successfully."
exit 0
