#!/usr/bin/env bash
#? Save a chapter (create pull request to draft branch)
#? Usage: tb2 chapter save -c CHAPTERNAME -b BOOKNAME [-q]
#? Opts:
#?   -c         CHAPTERNAME
#? config dependencies: GH_OWNER_NAME, TB2_OPERATION_BRANCH, PROJECT_NAME

set -euo pipefail


source "$ROOT/utils.sh"

bookName=""
chapterName=""

while getopts "c:" opt; do
  case $opt in
  c)
    chapterName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

if [[ -z "${bookName}" ]] || [[ -z "${chapterName}" ]]; then
  warn "Both -b BOOKNAME and -c CHAPTERNAME are required."
  info "Exit."
  exit 1
fi

log "Checking for config..."

useConf GH_OWNER_NAME name
useConf TB2_OPERATION_BRANCH branch
useConf PROJECT_NAME projectName

log "done."

chapterBranch="chapter/$chapterName"

info "Saving chapter: $chapterName in book: $bookName"
log "Creating pull request from '$chapterBranch' to '$branch'..."

run gh_createPR "$projectName" "$branch" "$chapterBranch"\
  "Add chapter: $chapterName ($bookName)" \
  "This PR adds chapter $chapterName to book $bookName."
log "done."
info "Chapter '$chapterName' saved successfully."
exit 0
