#!/usr/bin/env bash
#? Save a chapter (create pull request to draft branch)
#? Usage: tb2 chapter save -c CHAPTERNAME -b BOOKNAME 
#? Opts:
#?   -c         CHAPTERNAME
#? config dependencies: GH_OWNER_NAME, TB2_OPERATION_BRANCH

set -euo pipefail


. "$ROOT/utils.sh"

bookName=""
chapterName=""

while getopts "c:b:" opt; do
  case $opt in
	b)
		bookName="$OPTARG"
		;;
  c)
    chapterName="$OPTARG"
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done

if [ -z "${bookName}" ] || [ -z "${chapterName}" ]; then
  warn "Both -b BOOKNAME and -c CHAPTERNAME are required."
  info "Exit."
  exit 1
fi

log "Checking for config..."

useConf GH_OWNER_NAME name
useConf GH_REPO_NAME repoName
useConf TB2_OPERATION_BRANCH branch

log "done."

chapterBranch="chapter/$chapterName"

info "Saving chapter: $chapterName in book: $bookName"
log "Creating pull request from '$chapterBranch' to '$branch'..."

run gh_createPR "$name/$repoName" "$branch" "$chapterBranch"\
  "Add chapter: $chapterName ($bookName)" \
  "This PR adds chapter $chapterName to book $bookName."
log "done."
info "Chapter '$chapterName' saved successfully."
exit 0
