#!/usr/bin/env bash
#? Usage: tb2 page <subcmd> [options]
#? Subcommands:
#?   new       Create a new page
#?   save      Save a page (commit and push)
#?   list      List pages in a chapter

set -euo pipefail


. "$ROOT/utils.sh"

case "${1:-}" in
"")
  warn "No subcmd provided for 'page'"
  exit 1
  ;;
"new")
  shift
  "$ROOT/subcmds/page.d/subcmds/new" "$@"
  ;;
"save")
  shift
  "$ROOT/subcmds/page.d/subcmds/save" "$@"
  ;;
"list")
  shift
  "$ROOT/subcmds/page.d/subcmds/list" "$@"
  ;;
*)
  warn "Unknown subcmd '$1' for 'page'"
  exit 1
  ;;
esac
