#!/usr/bin/env bash

#? Usage: tb2 book <subcmd> [options]
#? Subcommands:
#?   new       Create a new book project
#?   list      List existing book projects
#? Opts:
#?   -b        BOOKNAME

set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)/../.."
source "$base_dir/utils.sh"

case "${1:-}" in
  "")
    warn "No subcmd provided for 'book'"
    exit 1
    ;;
  "new")
    shift
    "$base_dir/subcmds/book.d/subcmds/new" "$@"
    ;;
  "list")
    shift
    "$base_dir/subcmds/book.d/subcmds/list" "$@"
    ;;
  *)
    warn "Unknown subcmd '$1' for 'book'"
    exit 1
    ;;
esac
