#!/usr/bin/env bash

#? Usage: tb2 book <subcmd> [options]
#? Subcommands:
#?   new       Create a new book project
#?   list      List existing book projects

set -euo pipefail


source "$ROOT/utils.sh"

case "${1:-}" in
"")
  warn "No subcmd provided for 'book'"
  exit 1
  ;;
"new")
  shift
  "$ROOT/subcmds/book.d/subcmds/new" "$@"
  ;;
"list")
  shift
  "$ROOT/subcmds/book.d/subcmds/list" "$@"
  ;;
*)
  warn "Unknown subcmd '$1' for 'book'"
  exit 1
  ;;
esac
