#!/usr/bin/env bash
#? List existing book both remote and local
#? Usage: tb2 book list
#? config dependencies: GH_OWNER_NAME, MDBOOK_SERIES_NAME, MDBOOK_SRC_DIR

set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../.."
source "$base_dir/utils.sh"

log "Checking for config..."
checkConf true "MDBOOK_SRC_DIR" "PROJECT_NAME"
srcDir=$("$base_dir/tb2" config get 'MDBOOK_SRC_DIR')
projectName=$("$base_dir/tb2" config get 'PROJECT_NAME')
mustVar true "srcDir" "projectName"
log "done."

info "=Remote [GitHub Issues]="
log "=========================="
if gh_isManualMode; then
  info "Remote list is disabled in manual mode."
else
  run gh_findIssue "$projectName" "Book:"
fi
info "=Local [mdBook directory]="
log "=========================="
find "${srcDir:-src}" -maxdepth 1 -mindpth 1 -type d -print0 | while IFS= read -r -d '' bookPath; do
	bookPath=$(basename "$bookPath")
	log $bookPath
done
log "========================"
exit 0
