#!/usr/bin/env bash
#? List existing book both remote and local
#? Usage: tb2 book list
#? config dependencies: GH_OWNER_NAME, MDBOOK_SERIES_NAME, MDBOOK_SRC_DIR

set -euo pipefail


source "$ROOT/utils.sh"

log "Checking for config..."

useConf MDBOOK_SRC_DIR srcDir
useConf PROJECT_NAME projectName
log "done."

info "=Remote [GitHub Issues]="
log "=========================="
if gh_isManualMode; then
  info "Remote list is disabled in manual mode."
else
  run gh_findIssue "$projectName" "Book:"
fi
info "=Local [mdBook directory]="
log "=========================="
find "${srcDir:-src}" -maxdepth 1 -mindepth 1 -type d -print0 | while IFS= read -r -d '' bookPath; do
	bookPath=$(basename "$bookPath")
	log "$bookPath"
done
log "========================"
exit 0
