#!/usr/bin/env bash
#? List existing book both remote and local
#? Usage: tb2 book list
#? config dependencies: GH_OWNER_NAME, MDBOOK_SERIES_NAME, MDBOOK_SRC_DIR

set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)/../../.."
source "$base_dir/utils.sh"

seriesName=$("$base_dir/tb2" config get 'MDBOOK_SERIES_NAME')
srcDir=$("$base_dir/tb2" config get 'MDBOOK_SRC_DIR')
name=$("$base_dir/tb2" config get 'GH_OWNER_NAME')

log "Checking for config..."
checkConf true "MDBOOK_SERIES_NAME" "MDBOOK_SRC_DIR" "GH_OWNER_NAME"
mustVar true "seriesName" "srcDir" "name"
log "done."

info "=Remote [GitHub Projects]="
log "=========================="
run "gh project list --owner \"${name}\" | grep \"${seriesName}-\""

info "=Local [mdBook directory: ./${base_dir}/]="
run "ls -d ./${srcDir:-src}/*/ | grep \"${seriesName}-\" || echo 'No local books found.'"
log "========================"
exit 0