#!/usr/bin/env bash
#? Create a new book project
#? Usage: tb2 book new -b BOOKNAME
#? Opts:
#?   -b         BOOKNAME
#?   -q         exit if config variables are missing.
#? config dependencies: MDBOOK_SERIESNAME, GITHUB_OWNERNAME, MDBOOK_SRC_DIR, TB2_OPERATION_BRANCH
set -euo pipefail

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)/../../.."
source "$base_dir/utils.sh"

bookname=""
while getopts "b:q" opt; do
  case $opt in
    b)
      bookname="$OPTARG"
      ;;
    q)
      exit_missConf=true
      ;;
    \?)
      warn "Unknown option: -$OPTARG"
      exit 1
      ;;
  esac
done
if [[ -z "${bookname}" ]]; then
  warn "Book name via -b opt is required."
  info "Exit."
  exit 1
fi

seriesName=$("$base_dir/tb2" config get 'MDBOOK_SERIESNAME')
name=$("$base_dir/tb2" config get 'GITHUB_OWNERNAME')
srcDir=$("$base_dir/tb2" config get 'MDBOOK_SRC_DIR')
branch=$("$base_dir/tb2" config get 'TB2_OPERATION_BRANCH')

log "Checking for config..."
checkConf true "MDBOOK_SERIESNAME" "GITHUB_OWNERNAME" "MDBOOK_SRC_DIR" "TB2_OPERATION_BRANCH"
mustVar true "seriesName" "name" "srcDir" "branch"
log "done."

info "Creating new book GitHub Project: $bookname"
run "gh project create --owner \"$name\" --public --title \"$seriesName-$bookname\" --description \"Book project '$bookname'\""
log "Checking status of the project creation..."
run "gh project list --owner=\"$name\" | grep -q \"$seriesName-$bookname\" >/dev/null 2>&1"
if [[ $? -ne 0 ]]; then
  error "Failed to create the project on GitHub."
  exit 1
fi
log "done."
log "Project created on GitHub successfully."

log "Checking for local directory..."

if [[ -d "$srcDir/$bookname" ]]; then
  warn "Directory '$srcDir/$bookname' already exists locally. Skipping mkdir."
else
  log "Creating local directory '$srcDir/$bookname'..."
  run "mkdir \"$srcDir/$bookname\""
  ls "$srcDir/$bookname" >/dev/null 2>&1 || {
    error "Failed to create or access local directory '$srcDir/$bookname'."
    exit 1
  }
fi
log "done."
ans=$(ask "Do you want to commit&push the repository now draft branch? (y/n)")
if [[ "$ans" != "y" && "$ans" != "Y" ]]; then
  info "Exit."
  exit 0
fi
log "Using branch: $branch"
log "Checking if exist of branch name..."
if [[ "$(git rev-parse --abbrev-ref HEAD 2>/dev/null||echo)" != "$branch" ]]; then
  log "Branch '$branch' is not current branch."
  log "Checking for branch existence..."
  if git branch --list "$branch" >/dev/null 2>&1; then
    log "Branch '$branch' exists."
  else
    log "Branch '$branch' does not exist."
    ans=$(ask "Create branch[c] or Exit[e]?")
    if [[ "$ans" == "c" || "$ans" == "C" ]]; then
      run "git switch -c $branch"
      log "done."
    else
      info "Exit."
      exit 0
    fi
  fi
  log "Switching to branch '$branch'..."
  run "git switch $branch"
  log "done."
else
  log "Already on branch '$branch'."
  log "done."
fi

run "git add \"$srcDir/$bookname\""
run "git commit -m \"Initial commit for book $bookname\""
run "git push -u origin $branch"
log "done."
info "New book project '$bookname' created successfully."
exit 0