#!/usr/bin/env bash
#? Create a new book project
#? Usage: tb2 book new -b BOOKNAME [-a]
#? Opts:
#?   -b         book name
#?   -a         auto commit flag
#?   -t         with template
#? config dependencies: GH_OWNER_NAME,GH_REPO_NAME, MDBOOK_SRC_DIR, TB2_OPERATION_BRANCH
set -euo pipefail


. "$ROOT/utils.sh"

bookName=""
autoCommit="n"
useTemplate=false
while getopts "b:at" opt; do
  case $opt in
  b)
    bookName="$OPTARG"
    ;;
  a)
    autoCommit="y"
    ;;
  t)
    useTemplate=true
    ;;
  \?)
    warn "Unknown option: -$OPTARG"
    exit 1
    ;;
  :)
    warn "Option -$OPTARG requires an argument."
    exit 1
    ;;
  esac
done
if [ -z "${bookName}" ]; then
  warn "Option -b requires an argument."
  log "Exit."
  exit 1
fi

log "Checking for config..."

useConf GH_OWNER_NAME name
useConf GH_REPO_NAME repoName
useConf MDBOOK_SRC_DIR srcDir
useConf TB2_OPERATION_BRANCH branch

log "done."

log "Creating new book Issue: $bookName"
run gh_createIssue "$name/$repoName" "Book: $bookName" "New book project '$bookName'"
log "done."
log "Issue created on GitHub successfully."

log "Checking for local directory..."

if [ -d "$srcDir/$bookName" ]; then
  warn "Directory '$srcDir/$bookName' already exists locally. Skipping mkdir."
else
  log "Creating local directory '$srcDir/$bookName'..."
  run mkdir "$srcDir/$bookName"
  ls "$srcDir/$bookName" >/dev/null 2>&1 || {
    error "Failed to create or access local directory '$srcDir/$bookName'."
    exit 1
  }
fi
log "done."
if useTemplate; then
  log "Applying template..."
  tb2_applyTemplate "book" "$srcDir/$bookName/intro.md" "$bookName" "" ""
  log "done."
fi
ans="$autoCommit";
if ! tb2_isManualMode; then
  ask ans "Do you want to commit&push the repository now draft branch? (y/n)"
fi
if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
  git_chkBranch "$branch"
  run git add "$srcDir/$bookName"
  run git commit -m "Initial commit for book $bookName"
  run git push -u origin "$branch"
  log "done."
fi
info "New book project '$bookName' created."
exit 0
